packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx

feat: added a test partner account to account switcher

---

packages/core/src/App/Components/Layout/Header/account-actions.jsx
packages/core/src/App/Containers/Layout/header/default-header.jsx

Niloofar / Replace the "Deposit" button with the "withdrawal" button

---

packages/cashier/src/stores/general-store.js
packages/core/src/App/Containers/Layout/footer.jsx

-   Redirection the user when the user click on the cashier section
- …

Niloofar / some more features

---

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.jsx
packages/cashier/src/stores/account-transfer-store.js
packages/reports/jest.config.js

-   in this PR we add an opportunity to transfer funds from the partner's account to another trading account of this partner
-   [x] New feature …

george / rm64711 / Provide an opportunity to transfer funds from the partner's account to another trading account of this partner

---

packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx

-  Added an empty object check to prevent prop of undefined error
-   [X] Ensure all the tests are passing
-   [X] Bug fix
- …

Likhith/something not right error in POI screen

---

packages/cashier/src/stores/__tests__/account-transfer-store.spec.js
packages/cashier/src/stores/account-transfer-store.js

Vinu/removed Dmt5 for synthetic account from the transfer dropdown in cashier

---

packages/cashier/src/stores/__tests__/account-transfer-store.spec.js
packages/cashier/src/stores/account-transfer-store.js

Reverts akmal-binary/deriv-app#13

Revert "Vinu/removed Dmt5 for synthetic account from the transfer dropdown in cashier"

---

packages/components/src/components/contract-card/contract-card-items/contract-card-body.jsx
packages/shared/src/utils/constants/barriers.ts
packages/trader/src/Assets/Trading/Categories/trade-categories.jsx
packages/trader/src/Modules/Contract/Components/InfoBox/info-box-longcode.jsx
packages/trader/src/Modules/Trading/Components/Elements/purchase-button.jsx
packages/trader/src/Modules/Trading/Components/Form/Purchase/contract-info.jsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/strike-field.scss
packages/trader/src/Stores/Modules/Trading/Constants/validation-rules.js
packages/trader/src/sass/app/_common/components/contract-type-list.scss
packages/trader/src/sass/app/_common/components/strike.scss
packages/trader/src/sass/app/modules/trading-mobile.scss
packages/trader/src/sass/app/modules/trading.scss

-   Incorporated review comments

feat: :recycle: incorporated review comments

---

packages/components/src/components/contract-card/contract-card-items/contract-type-cell.jsx

fix: :bug: report title fix

---

packages/trader/src/Stores/Modules/Trading/Helpers/proposal.js

likhith/fix: :bug: resolved input validation failed error

---

packages/trader/src/Stores/Modules/Trading/trade-store.js

likhith/fix: :bug: strike price is empty when there is duration change

---

packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount-mobile.jsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount.jsx
packages/trader/src/Stores/Modules/Trading/Helpers/process.js
packages/trader/src/Stores/Modules/Trading/trade-store.js

fix: :bug: modified stake boundary calculation for vanilla opts

---

packages/trader/src/Stores/Modules/Trading/trade-store.js

likhith/fix: :bug: set strike value and list on error response

---

packages/trader/src/Stores/Modules/Trading/trade-store.js

likhith/fix: :bug: call proposal API on strike change

---

packages/trader/src/Assets/Trading/Categories/trade-categories.jsx

feat: changed vanilla trade description

---

packages/components/src/components/data-list/data-list-cell.jsx

fix: :bug: added missing label

---

packages/trader/src/Modules/Trading/Containers/trade-params-mobile.jsx

-  Changed the field name in case of vanilla

likhith/fix: :bug: corrected field name

---

packages/components/src/components/data-list/data-list-cell.jsx
packages/components/src/components/progress-slider-mobile/progress-ticks-mobile.jsx
packages/reports/src/Constants/data-table-constants.js

-   Refactored code to support additional configs

fix: :bug: refactored code to support additional configs

---

packages/core/src/Components/markers/marker-spot-label.jsx

fix: :bug: incorporated + sign in reports

---

packages/trader/src/Stores/Modules/Trading/trade-store.js

fix: :bug: resolved issue with double error message

---

packages/trader/src/Modules/Contract/Components/InfoBox/info-box-longcode.jsx
packages/trader/src/Modules/Trading/Components/Form/Purchase/contract-info.jsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/strike.jsx
packages/trader/src/Modules/Trading/Containers/strike-param-modal.jsx

feat: modified the content as per figma

---

packages/components/src/components/popover/popover.tsx
packages/components/src/components/types/popover.types.ts
packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount.jsx
packages/trader/src/Modules/Trading/Containers/trade-params-mobile.jsx
packages/trader/src/sass/app/modules/trading-mobile.scss

feat: :art: added tooltip for stake

---

packages/trader/src/Assets/Trading/Categories/trade-categories.jsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/strike.jsx
packages/trader/src/Modules/Trading/Containers/strike-param-modal.jsx

feat: content update as per figma

---

packages/trader/src/Modules/Trading/Containers/trade.jsx
packages/trader/src/sass/app/modules/smart-chart.scss

feat: :lipstick: set the layout for vanilla trade

---

packages/trader/src/AppV2/Components/InfoModal/index.ts
packages/trader/src/AppV2/Components/InfoModal/info-modal.scss
packages/trader/src/AppV2/Components/InfoModal/info-modal.tsx
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx

fix: earn payout bottom modal

---

packages/core/src/Stores/contract-replay-store.js
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx
packages/trader/src/AppV2/Hooks/useContractDetails.ts

Ahmad/useContractDetails Hook

---

packages/trader/src/AppV2/Components/CardWrapper/card-wrapper.scss
packages/trader/src/AppV2/Components/OrderDetails/index.ts
packages/trader/src/AppV2/Components/OrderDetails/order-details.scss
packages/trader/src/AppV2/Components/OrderDetails/order-details.tsx
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx
packages/trader/src/AppV2/Hooks/useOrderDetails.ts

chore: useOrderDetails hook with order details

---

packages/trader/src/AppV2/Components/CardWrapper/card-wrapper.scss
packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.scss
packages/trader/src/AppV2/Components/OrderDetails/order-details.scss
packages/trader/src/AppV2/Components/PayoutInfo/index.ts
packages/trader/src/AppV2/Components/PayoutInfo/payout-info.scss
packages/trader/src/AppV2/Components/PayoutInfo/payout-info.tsx
packages/trader/src/AppV2/Components/TakeProfitHistory/take-profit-history.scss
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.scss

fix: styling and css

---

packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.tsx
packages/trader/src/AppV2/Components/OrderDetails/order-details.scss
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx

chore: entry exit details dynamic val

---

packages/trader/src/AppV2/Utils/__tests__/helper.spec.ts
packages/trader/src/AppV2/Utils/helper.ts

helper fix

---

packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.tsx

Ts fix entry exit details

---

packages/trader/src/AppV2/Containers/ContractDetails/__tests__/contract-details.spec.tsx

chore: contract details test case

---

packages/trader/src/AppV2/Utils/__tests__/helper.spec.ts
packages/trader/src/AppV2/Utils/helper.ts

fix helper

---

packages/trader/src/AppV2/Containers/ContractDetails/__tests__/contract-details.spec.tsx
packages/trader/src/AppV2/app.tsx

chore: removing unused import

---

packages/trader/src/AppV2/Hooks/useContractDetails.ts

chore: sonar fix

---

packages/components/src/components/remaining-time/remaining-time.tsx
packages/trader/src/AppV2/Components/CardWrapper/card-wrapper.scss
packages/trader/src/AppV2/Components/ContractDetailsFooter/contract-details-footer.tsx
packages/trader/src/AppV2/Components/DealCancellation/deal-cancellation.tsx
packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details-row.tsx
packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.scss
packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.tsx
packages/trader/src/AppV2/Components/PayoutInfoModal/payout-info-modal.scss
packages/trader/src/AppV2/Components/StopLoss/stop-loss.tsx
packages/trader/src/AppV2/Components/TakeProfit/take-profit.tsx
packages/trader/src/AppV2/Components/TakeProfitHistory/take-profit-history.scss
packages/trader/src/AppV2/Containers/ContractDetails/__tests__/contract-details.spec.tsx
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.scss
packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx
packages/trader/src/AppV2/Hooks/__tests__/useOrderDetails.spec.tsx
packages/trader/src/AppV2/Hooks/useContractDetails.ts
packages/trader/src/AppV2/Hooks/useOrderDetails.ts
packages/trader/src/AppV2/Utils/contract-details-config.ts

F contract details

---

packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx

stepper fix

---

packages/trader/src/AppV2/Components/CardWrapper/__tests__/card-wrapper.spec.tsx
packages/trader/src/AppV2/Components/ContractDetailsFooter/__tests__/contract-details-footer.spec.tsx
packages/trader/src/AppV2/Components/DealCancellation/__tests__/deal-cancellation.spec.tsx
packages/trader/src/AppV2/Components/PayoutInfo/__tests__/payout-info.spec.tsx
packages/trader/src/AppV2/Components/PayoutInfoModal/__tests__/payout-info-model.spec.tsx
packages/trader/src/AppV2/Components/RiskManagementItem/__tests__/risk-management-item.spec.tsx
packages/trader/src/AppV2/Components/StopLoss/__tests__/stop-loss.spec.tsx
packages/trader/src/AppV2/Components/TakeProfit/__tests__/take-profit.spec.tsx
packages/trader/src/AppV2/Components/TakeProfitHistory/__tests__/take-profit-history.spec.tsx
packages/trader/src/AppV2/Containers/Chart/__tests__/chart-placeholder.spec.tsx
packages/trader/src/AppV2/Containers/ContractDetails/__tests__/contract-details.spec.tsx

fix: review fix

---

packages/trader/src/AppV2/Components/DraggableList/__tests__/draggable-list.spec.tsx
packages/trader/src/AppV2/Components/DraggableList/draggable-list-item.tsx
packages/trader/src/AppV2/Components/DraggableList/draggable-list.scss
packages/trader/src/AppV2/Components/DraggableList/draggable-list.tsx
packages/trader/src/AppV2/Components/TradeTypeList/__tests__/trade-type-list-item.spec.tsx
packages/trader/src/AppV2/Components/TradeTypeList/__tests__/trade-type-list.spec.jsx
packages/trader/src/AppV2/Components/TradeTypeList/index.ts
packages/trader/src/AppV2/Components/TradeTypeList/trade-type-list-item.tsx
packages/trader/src/AppV2/Components/TradeTypeList/trade-type-list.scss
packages/trader/src/AppV2/Components/TradeTypeList/trade-type-list.tsx
packages/trader/src/AppV2/Containers/Trade/trade.tsx

Akmal / add edit trade types page

---

package-lock.json
packages/bot-web-ui/package.json
packages/core/package.json
packages/trader/package.json

Pull 18508
